irmaUrl: http://localhost:3846/irma
irmaProductionMode: false
port: 3846
oidcClients:
  - id: my-client
    secret: foobar
    redirectUris:
      - http://localhost:8080
    scopes:
      - openid
      - pbdf.gemeente.personalData.initials
      - pbdf.gemeente.personalData.surname
      - pbdf.pbdf.email.email
oidcIssuer: irma-oidc-server
oauthHmacSecret: some-super-cool-secret-that-nobody-knows
#jwtPrivateKey: |-
#  -----BEGIN RSA PRIVATE KEY-----
#  FILL_IN..
#  -----END RSA PRIVATE KEY-----
